# Generated by Django 5.2.3 on 2025-06-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgingcriteria',
            name='guide_questions',
            field=models.TextField(blank=True, help_text='Optional guiding questions to assist judges in scoring this criterion'),
        ),
    ]
