# Generated by Django 5.2.3 on 2025-06-24 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0002_judgingcriteria_guide_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='judge_type',
            field=models.CharField(choices=[('quantum_expert', 'Quantum Expert'), ('general_judge', 'General Judge'), ('public', 'Public Judge')], default='general_judge', help_text='Determines which criteria this judge can evaluate', max_length=20),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(help_text='Score from 1–5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
